# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed672ce27745809020b497e1ff5bdd0d8a91e15fef850c9555d4fdf07c723dec2bf71555e96247d1002df2bf156413981e0281a75f17fefb4e093e08be41fd6b

test:
  secret_key_base: cf6f874ae636826ac4f2e893f49a9abd444000d5950c81da64647d5bec89c3fb24756bc10ee7fcd317ef763acc00daea5963b689c47b43efb50a89279257b56f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
